---
- name: Download bootstrap script
  get_url:
    dest: /tmp/bootstrap.sh
    mode: +x
    url: https://raw.githubusercontent.com/kwanpham2195/dots/main/bootstrap.sh
    force: yes

- name: Run bootstrap script
  shell: /tmp/bootstrap.sh
